#!/usr/bin/env bash
# Script that displays to infinity and beyond indefinitely, w sleep 2, I AM INVINCIBLE!

while true; do
        echo "To infinity and beyond"
        sleep 2
	trap "echo I am invincible!!!" SIGTERM
		
done

