#!/usr/bin/env bash
#Fizz on 3s Buzz on 5s Fizzbuzz on 15s
x=0


for x in {1..100}; do
 
if (( x % 15 == 0 ))
	then
	echo "FizzBuzz"	
elif (( x % 3 == 0 ))
	then
	echo "Fizz"
elif (( x % 5 == 0))
	then
	echo "Buzz"
else echo "$x"

fi
done
