#!/usr/bin/env bash
#uses a while loop to print 10 times 'Holberton School, 4 prints bad luck, 8 prints good luck'
x=1

while [ $x -le 5 ]
do
  echo "Holberton School"
  x=$(( x + 1 ))
  if [ $x = 3 ]
  then
  echo "bad luck"
  elif [ $x = 5 ] 
  then
  echo "good luck"
  else 
  echo "Holberton School"
  fi
done
