#!/usr/bin/env bash
#uses a while loop to iterate 1-20 and place bad luck between numbers

x=1

while [ $x -le 20 ]
do 
   echo "$x"
   case $x in
                4)
                    echo "bad luck from China"
                    ;;
               9)
                    echo "bad luck from Japan"
                    ;;
                17)
                    echo "bad luck from Italy"
                    ;;
                *)
          esac
   x=$(( x + 1 ))
done
