#!/usr/bin/env bash
#uses a while loop to iterate 1-20 and place bad luck between numbers

x=1

while [ $x -le 20 ]
do
  
   echo "$x"
   x=$(( $x + 1 ))

  case $x  in
                5)
                    echo "bad luck from China"

                    ;;
               10)
                    echo "bad luck from Japan"

                    ;;
                18)
                    echo "bad luck from Italy"

                    ;;
                *)
          esac
done
