#!/usr/bin/env bash
#Replicates a clock by iterating 60 seconds and increasing hour by one
HOUR=0
MINUTES=1

echo "Hour: $HOUR"
while [ $HOUR -le 12 ]
  do
  echo "Hour: $HOUR"
  MINUTES=1
  while [ $MINUTES -le 59 ]
        do
        echo "$MINUTES"	
        MINUTES=$((MINUTES+1))
	done
  HOUR=$((HOUR+1))
done
